name: pro-actions

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup npm
      run: npm install -g yarn
    - name: Setup Nodejs with yarn caching
      uses: actions/setup-node@v2
      with:
        node-version: "18"
        cache: npm

    - name: Install dependencies
      run: npm install
    - name: build
      if: ${{ github.event_name == 'push' }}
      env:
         CI: false
      run: npm run build --mode=production
    - uses: docker/login-action@v2.1.0
      if: ${{ github.event_name == 'push' }}
      with:
        registry: registry.digitalocean.com
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}        
    - uses: docker/setup-buildx-action@v2.2.1
      if: ${{ github.event_name == 'push' }}
    - uses: docker/build-push-action@v3.2.0
      if: ${{ github.event_name == 'push' }}
      with:
        context: .
        push: true
        tags: registry.digitalocean.com/geafe/gestion_administrativa:${{ github.sha }},registry.digitalocean.com/geafe/gestion_administrativa:latest-pro
    - name: Image digest
      if: ${{ github.event_name == 'push' }}
      run: echo ${{ steps.docker_build.outputs.digest }}
